[pytest]
addopts = -ra --reuse-db --ds=config.settings.test

DJANGO_SETTINGS_MODULE = config.settings.test

python_files = test_*.py tests.py *_test.py
python_classes = Test*
python_functions = test_*

testpaths = tests
