# Generated by Django 5.1.3 on 2026-07-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("application", "Application"),
                    ("consulting", "Consulting"),
                    ("opportunity", "Opportunity"),
                    ("scraping", "Scraping"),
                    ("system", "System"),
                    ("messaging", "Messaging"),
                ],
                default="system",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("application_status", "Application Status"),
                    ("consulting_response", "Consulting Response"),
                    ("new_opportunity", "New Opportunity"),
                    ("scraping_complete", "Scraping Complete"),
                    ("system", "System Announcement"),
                    ("deadline_reminder", "Deadline Reminder"),
                    ("new_message", "New Message"),
                ],
                max_length=30,
            ),
        ),
    ]
