# Generated by Django 5.1.3 on 2026-05-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=50)),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                ("record_id", models.IntegerField(null=True)),
                ("data_before", models.JSONField(blank=True, default=dict)),
                ("data_after", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("user_agent", models.TextField(blank=True)),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "managed": True,
            },
        ),
    ]
