# Generated by Django 5.1.3 on 2026-06-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_profile_preferred_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="company",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="profile",
            name="preferred_language",
            field=models.CharField(default="en", max_length=2),
        ),
    ]
