# Generated by Django 5.1.3 on 2026-07-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_profile_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="notify_new_message",
            field=models.BooleanField(default=True),
        ),
    ]
