# Generated by Django 5.1.3 on 2026-06-25 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remove_duplicate_applications(apps, schema_editor):
    """
    Before adding the blanket unique constraint on (user_id, opportunity_id),
    remove duplicate rows — keep the most recently updated one per pair and
    delete the rest.
    """
    Application = apps.get_model('applications', 'Application')
    seen = {}
    # Order oldest first so the last one we keep is the newest
    for app in Application.objects.order_by('updated_at'):
        key = (app.user_id, app.opportunity_id)
        if key in seen:
            # Delete the previously-seen (older) record
            Application.objects.filter(pk=seen[key]).delete()
        seen[key] = app.pk


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_application_shortlisted_status"),
        ("opportunities", "0004_fundingopportunity_city"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="application_messages/"
                    ),
                ),
                ("attachment_name", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "application_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="application",
            name="uniq_active_application_per_user_opportunity",
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("shortlisted", "Shortlisted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        # Deduplicate before adding the blanket unique constraint
        migrations.RunPython(
            remove_duplicate_applications,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("user", "opportunity"),
                name="uniq_active_application_per_user_opportunity",
            ),
        ),
        migrations.AddField(
            model_name="applicationmessage",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="applications.application",
            ),
        ),
        migrations.AddField(
            model_name="applicationmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]