# Generated by Django 5.1.3 on 2026-05-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FundingOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(db_index=True, max_length=500)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("GEF", "Global Environment Facility"),
                            ("GCF", "Green Climate Fund"),
                            ("OECD", "OECD"),
                            ("CLIMATE_FUND", "Climate Fund"),
                            ("WORLD_BANK", "World Bank"),
                            ("AFD", "Agence Française de Développement"),
                            ("EU", "European Union"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "country",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("deadline", models.DateField(blank=True, db_index=True, null=True)),
                ("eligibility_criteria", models.TextField(blank=True)),
                ("required_documents", models.TextField(blank=True)),
                (
                    "funding_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("grant", "Grant"),
                            ("loan", "Loan"),
                            ("concessional", "Concessional"),
                            ("blended", "Blended"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("sector", models.CharField(blank=True, db_index=True, max_length=100)),
                ("completeness_score", models.IntegerField(default=0)),
                ("hash", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=1000)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name_plural": "Funding Opportunities",
                "db_table": "funding_opportunities",
                "ordering": ["-created_at"],
            },
        ),
    ]
