# Generated by Django 5.1.3 on 2026-06-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0004_fundingopportunity_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundingopportunity",
            name="source",
            field=models.CharField(
                choices=[
                    ("GEF", "Global Environment Facility"),
                    ("GCF", "Green Climate Fund"),
                    ("OECD", "OECD"),
                    ("WORLD_BANK", "World Bank"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
